2024-08-19 14:41:22-INFO-[<module>():9]-Starting Service
2024-08-19 14:41:30-ERROR-[add_movie():43]-error in Invalid crypto padding
Traceback (most recent call last):
  File "C:\Users\anit.dias\PycharmProjects\MoiveBooking\.venv\Lib\site-packages\jwt\api_jws.py", line 282, in _load
    signature = base64url_decode(crypto_segment)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anit.dias\PycharmProjects\MoiveBooking\.venv\Lib\site-packages\jwt\utils.py", line 33, in base64url_decode
    return base64.urlsafe_b64decode(input_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anit.dias\AppData\Local\Programs\Python\Python312\Lib\base64.py", line 134, in urlsafe_b64decode
    return b64decode(s)
           ^^^^^^^^^^^^
  File "C:\Users\anit.dias\AppData\Local\Programs\Python\Python312\Lib\base64.py", line 88, in b64decode
    return binascii.a2b_base64(s, strict_mode=validate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
binascii.Error: Incorrect padding

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\anit.dias\PycharmProjects\MoiveBooking\scripts\core\engine\services\add_movies.py", line 31, in add_movie
    decoded_token = jwt.decode(token, jwt_key, algorithms=algorithm)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anit.dias\PycharmProjects\MoiveBooking\.venv\Lib\site-packages\jwt\api_jwt.py", line 211, in decode
    decoded = self.decode_complete(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anit.dias\PycharmProjects\MoiveBooking\.venv\Lib\site-packages\jwt\api_jwt.py", line 152, in decode_complete
    decoded = api_jws.decode_complete(
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anit.dias\PycharmProjects\MoiveBooking\.venv\Lib\site-packages\jwt\api_jws.py", line 199, in decode_complete
    payload, signing_input, header, signature = self._load(jwt)
                                                ^^^^^^^^^^^^^^^
  File "C:\Users\anit.dias\PycharmProjects\MoiveBooking\.venv\Lib\site-packages\jwt\api_jws.py", line 284, in _load
    raise DecodeError("Invalid crypto padding") from err
jwt.exceptions.DecodeError: Invalid crypto padding
2024-08-19 14:43:11-INFO-[<module>():11]-Stopping Service
2024-08-19 14:43:13-INFO-[<module>():9]-Starting Service
2024-08-19 14:44:50-ERROR-[add_movie():43]-error in cannot encode object: datetime.date(2024, 8, 19), of type: <class 'datetime.date'>
Traceback (most recent call last):
  File "C:\Users\anit.dias\PycharmProjects\MoiveBooking\scripts\core\engine\services\add_movies.py", line 41, in add_movie
    movie_collection.insert_one(movie_entry)
  File "C:\Users\anit.dias\PycharmProjects\MoiveBooking\.venv\Lib\site-packages\pymongo\collection.py", line 658, in insert_one
    self._insert_one(
  File "C:\Users\anit.dias\PycharmProjects\MoiveBooking\.venv\Lib\site-packages\pymongo\collection.py", line 598, in _insert_one
    self.__database.client._retryable_write(
  File "C:\Users\anit.dias\PycharmProjects\MoiveBooking\.venv\Lib\site-packages\pymongo\mongo_client.py", line 1575, in _retryable_write
    return self._retry_with_session(retryable, func, s, bulk, operation, operation_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anit.dias\PycharmProjects\MoiveBooking\.venv\Lib\site-packages\pymongo\mongo_client.py", line 1461, in _retry_with_session
    return self._retry_internal(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anit.dias\PycharmProjects\MoiveBooking\.venv\Lib\site-packages\pymongo\_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anit.dias\PycharmProjects\MoiveBooking\.venv\Lib\site-packages\pymongo\mongo_client.py", line 1507, in _retry_internal
    ).run()
      ^^^^^
  File "C:\Users\anit.dias\PycharmProjects\MoiveBooking\.venv\Lib\site-packages\pymongo\mongo_client.py", line 2353, in run
    return self._read() if self._is_read else self._write()
                                              ^^^^^^^^^^^^^
  File "C:\Users\anit.dias\PycharmProjects\MoiveBooking\.venv\Lib\site-packages\pymongo\mongo_client.py", line 2470, in _write
    return self._func(self._session, conn, self._retryable)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anit.dias\PycharmProjects\MoiveBooking\.venv\Lib\site-packages\pymongo\collection.py", line 586, in _insert_command
    result = conn.command(
             ^^^^^^^^^^^^^
  File "C:\Users\anit.dias\PycharmProjects\MoiveBooking\.venv\Lib\site-packages\pymongo\helpers.py", line 342, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anit.dias\PycharmProjects\MoiveBooking\.venv\Lib\site-packages\pymongo\pool.py", line 1017, in command
    self._raise_connection_failure(error)
  File "C:\Users\anit.dias\PycharmProjects\MoiveBooking\.venv\Lib\site-packages\pymongo\pool.py", line 989, in command
    return command(
           ^^^^^^^^
  File "C:\Users\anit.dias\PycharmProjects\MoiveBooking\.venv\Lib\site-packages\pymongo\network.py", line 152, in command
    request_id, msg, size, max_doc_size = message._op_msg(
                                          ^^^^^^^^^^^^^^^^
  File "C:\Users\anit.dias\PycharmProjects\MoiveBooking\.venv\Lib\site-packages\pymongo\message.py", line 758, in _op_msg
    return _op_msg_uncompressed(flags, command, identifier, docs, opts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bson.errors.InvalidDocument: cannot encode object: datetime.date(2024, 8, 19), of type: <class 'datetime.date'>
2024-08-19 14:53:35-ERROR-[add_movie():43]-error in cannot encode object: datetime.date(2024, 8, 19), of type: <class 'datetime.date'>
Traceback (most recent call last):
  File "C:\Users\anit.dias\PycharmProjects\MoiveBooking\scripts\core\engine\services\add_movies.py", line 41, in add_movie
    movie_collection.insert_one(movie_entry)
  File "C:\Users\anit.dias\PycharmProjects\MoiveBooking\.venv\Lib\site-packages\pymongo\collection.py", line 658, in insert_one
    self._insert_one(
  File "C:\Users\anit.dias\PycharmProjects\MoiveBooking\.venv\Lib\site-packages\pymongo\collection.py", line 598, in _insert_one
    self.__database.client._retryable_write(
  File "C:\Users\anit.dias\PycharmProjects\MoiveBooking\.venv\Lib\site-packages\pymongo\mongo_client.py", line 1575, in _retryable_write
    return self._retry_with_session(retryable, func, s, bulk, operation, operation_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anit.dias\PycharmProjects\MoiveBooking\.venv\Lib\site-packages\pymongo\mongo_client.py", line 1461, in _retry_with_session
    return self._retry_internal(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anit.dias\PycharmProjects\MoiveBooking\.venv\Lib\site-packages\pymongo\_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anit.dias\PycharmProjects\MoiveBooking\.venv\Lib\site-packages\pymongo\mongo_client.py", line 1507, in _retry_internal
    ).run()
      ^^^^^
  File "C:\Users\anit.dias\PycharmProjects\MoiveBooking\.venv\Lib\site-packages\pymongo\mongo_client.py", line 2353, in run
    return self._read() if self._is_read else self._write()
                                              ^^^^^^^^^^^^^
  File "C:\Users\anit.dias\PycharmProjects\MoiveBooking\.venv\Lib\site-packages\pymongo\mongo_client.py", line 2470, in _write
    return self._func(self._session, conn, self._retryable)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anit.dias\PycharmProjects\MoiveBooking\.venv\Lib\site-packages\pymongo\collection.py", line 586, in _insert_command
    result = conn.command(
             ^^^^^^^^^^^^^
  File "C:\Users\anit.dias\PycharmProjects\MoiveBooking\.venv\Lib\site-packages\pymongo\helpers.py", line 342, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anit.dias\PycharmProjects\MoiveBooking\.venv\Lib\site-packages\pymongo\pool.py", line 1017, in command
    self._raise_connection_failure(error)
  File "C:\Users\anit.dias\PycharmProjects\MoiveBooking\.venv\Lib\site-packages\pymongo\pool.py", line 989, in command
    return command(
           ^^^^^^^^
  File "C:\Users\anit.dias\PycharmProjects\MoiveBooking\.venv\Lib\site-packages\pymongo\network.py", line 152, in command
    request_id, msg, size, max_doc_size = message._op_msg(
                                          ^^^^^^^^^^^^^^^^
  File "C:\Users\anit.dias\PycharmProjects\MoiveBooking\.venv\Lib\site-packages\pymongo\message.py", line 758, in _op_msg
    return _op_msg_uncompressed(flags, command, identifier, docs, opts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bson.errors.InvalidDocument: cannot encode object: datetime.date(2024, 8, 19), of type: <class 'datetime.date'>
2024-08-19 14:56:28-INFO-[<module>():11]-Stopping Service
2024-08-19 14:56:31-INFO-[<module>():9]-Starting Service
2024-08-19 14:58:22-INFO-[<module>():11]-Stopping Service
2024-08-19 15:07:01-INFO-[<module>():9]-Starting Service
2024-08-19 15:09:52-INFO-[<module>():11]-Stopping Service
2024-08-19 15:09:55-INFO-[<module>():9]-Starting Service
2024-08-19 15:10:43-INFO-[<module>():11]-Stopping Service
2024-08-19 15:10:45-INFO-[<module>():9]-Starting Service
2024-08-19 15:12:46-INFO-[<module>():11]-Stopping Service
2024-08-19 15:12:48-INFO-[<module>():9]-Starting Service
2024-08-19 15:13:14-INFO-[<module>():11]-Stopping Service
2024-08-19 15:13:16-INFO-[<module>():9]-Starting Service
2024-08-19 15:13:30-INFO-[<module>():11]-Stopping Service
2024-08-19 15:13:32-INFO-[<module>():9]-Starting Service
2024-08-19 15:15:49-INFO-[<module>():11]-Stopping Service
2024-08-19 15:15:51-INFO-[<module>():9]-Starting Service
2024-08-19 15:29:08-INFO-[<module>():11]-Stopping Service
2024-08-19 15:32:10-INFO-[<module>():9]-Starting Service
2024-08-19 15:32:42-INFO-[<module>():11]-Stopping Service
2024-08-19 15:32:44-INFO-[<module>():9]-Starting Service
2024-08-19 15:34:52-INFO-[<module>():11]-Stopping Service
2024-08-19 15:35:16-INFO-[<module>():9]-Starting Service
2024-08-19 15:35:40-INFO-[<module>():11]-Stopping Service
2024-08-19 15:41:35-INFO-[<module>():9]-Starting Service
2024-08-19 15:41:43-INFO-[<module>():11]-Stopping Service
2024-08-19 15:42:04-INFO-[<module>():9]-Starting Service
2024-08-19 15:43:04-INFO-[<module>():11]-Stopping Service
2024-08-19 15:43:09-INFO-[<module>():9]-Starting Service
2024-08-19 15:48:17-INFO-[<module>():11]-Stopping Service
2024-08-19 15:48:20-INFO-[<module>():9]-Starting Service
2024-08-19 15:48:42-INFO-[<module>():11]-Stopping Service
2024-08-19 15:49:01-INFO-[<module>():9]-Starting Service
2024-08-19 15:51:54-INFO-[<module>():11]-Stopping Service
2024-08-19 15:51:56-INFO-[<module>():9]-Starting Service
2024-08-19 15:56:07-INFO-[<module>():11]-Stopping Service
2024-08-19 15:56:09-INFO-[<module>():9]-Starting Service
2024-08-19 15:56:36-INFO-[<module>():11]-Stopping Service
2024-08-19 15:56:38-INFO-[<module>():9]-Starting Service
2024-08-19 15:57:10-INFO-[<module>():11]-Stopping Service
2024-08-19 15:57:12-INFO-[<module>():9]-Starting Service
2024-08-19 15:57:34-INFO-[<module>():11]-Stopping Service
2024-08-19 15:57:36-INFO-[<module>():9]-Starting Service
2024-08-19 16:04:33-INFO-[<module>():11]-Stopping Service
2024-08-19 16:20:43-INFO-[<module>():9]-Starting Service
2024-08-19 16:20:55-INFO-[<module>():11]-Stopping Service
2024-08-19 16:24:12-INFO-[<module>():9]-Starting Service
2024-08-19 16:28:01-INFO-[<module>():9]-Starting Service
2024-08-19 16:31:30-INFO-[<module>():9]-Starting Service
2024-08-19 16:33:00-INFO-[<module>():11]-Stopping Service
2024-08-19 16:33:31-INFO-[<module>():9]-Starting Service
2024-08-19 16:34:23-INFO-[<module>():11]-Stopping Service
2024-08-19 16:34:58-INFO-[<module>():9]-Starting Service
2024-08-19 16:35:54-INFO-[<module>():11]-Stopping Service
2024-08-19 16:38:13-INFO-[<module>():9]-Starting Service
2024-08-19 16:39:01-INFO-[<module>():11]-Stopping Service
2024-08-19 16:39:03-INFO-[<module>():9]-Starting Service
2024-08-19 16:40:55-INFO-[<module>():11]-Stopping Service
2024-08-19 16:43:58-INFO-[<module>():9]-Starting Service
2024-08-19 16:44:32-INFO-[<module>():11]-Stopping Service
2024-08-19 16:44:34-INFO-[<module>():9]-Starting Service
2024-08-19 17:14:40-INFO-[<module>():11]-Stopping Service
2024-08-19 18:10:47-INFO-[<module>():9]-Starting Service
2024-08-19 18:12:22-ERROR-[add_movie():37]-error in document must be an instance of dict, bson.son.SON, bson.raw_bson.RawBSONDocument, or a type that inherits from collections.MutableMapping
Traceback (most recent call last):
  File "C:\Users\anit.dias\PycharmProjects\MoiveBooking\scripts\core\engine\services\add_movies.py", line 35, in add_movie
    movie_collection.insert_one(movie)
  File "C:\Users\anit.dias\PycharmProjects\MoiveBooking\.venv\Lib\site-packages\pymongo\collection.py", line 652, in insert_one
    common.validate_is_document_type("document", document)
  File "C:\Users\anit.dias\PycharmProjects\MoiveBooking\.venv\Lib\site-packages\pymongo\common.py", line 549, in validate_is_document_type
    raise TypeError(
TypeError: document must be an instance of dict, bson.son.SON, bson.raw_bson.RawBSONDocument, or a type that inherits from collections.MutableMapping
2024-08-19 18:13:35-INFO-[<module>():11]-Stopping Service
2024-08-19 18:13:38-INFO-[<module>():9]-Starting Service
2024-08-19 18:15:43-INFO-[<module>():11]-Stopping Service
2024-08-19 18:15:55-INFO-[<module>():9]-Starting Service
2024-08-19 18:22:49-INFO-[<module>():11]-Stopping Service
2024-08-19 18:30:13-INFO-[<module>():9]-Starting Service
2024-08-19 18:37:23-INFO-[<module>():11]-Stopping Service
